
site_name:KochiOrgBook
site_url: https://www.KochiOrgBook.com
site_description: Project documentation with Markdown.
site_author: KochiOrgBookTeam

repo_url: https://github.com/anseela/KOBman/tree/master/docs
edit_uri: ""

theme:
    name: KochiOrgBook 
    highlightjs: true
    hljs_languages:
        - yaml
        - django
# Page tree
nav:
    - Home: index.md
        -ContactUs_ContributeWithUs: ContactUs_ContributeWithUs.md
    - User Guide:
        - ManuelSteps: user-guide/02_ManuelSteps.md
        - AutomatedScript: user-guide/03_AutomatedScript.md
        - Getting Started User Guide: user-guide/Getting Started User Guide.md
        - Maintainers-handbook: user-guide/Maintainers-handbook.md
        - Manual_steps: user-guide/Manual_steps.md
        - Proxy_ManuelSteps: user-guide/Proxy_ManuelSteps.md
    
    - KOBman:
        - README: KOBman/README.md
        


markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: mkdocs
        repo: mkdocs

copyright:
 

plugins:
    - search
